### ISSUE TITLE
Clickhouse driver doesn't working

### ISSUE THREAD

**Issue by jasondavindev** [sqlpad/sqlpad#1021]
Sqlpad docker image: `latest` tag
Clickhouse version: 21.6.4.26

When I try create a new connection using clickhouse driver the connection test fails shown me the error below

```
403: Code: 516, e.displayText() = DB::Exception: Invalid authentication: it is not allowed to use Authorization HTTP header and authentication via parameters simultaneously (version 21.6.4.26 (official build))
```

I chaged my clickhouse version to `20.3.9.70`, but the problem related here #915  remains - the databases and tables doesn't shown in the panel, but them are return in the connections request.

This issue doesn't worked for me #1011

**Comment by dengc367** [comment]
I use the `latest` sqlpad and the`latest`clickhouse, and I test successfully. Look at my connection setup screenshot, and I can query the sql with this connection successfully. 
my sqlpad connection setup screenshot:
![image](https://user-images.githubusercontent.com/1353036/121846156-21cea780-cd19-11eb-8d91-5ca495130d5c.png)

and my clickhouser server `user.xml` configuration:

```
<users>
        <testuser3>
                <password>testplpassword</password>
                <networks incl="networks" replace="replace">
                <ip>192.168.0.0/24</ip>
                <ip>10.0.0.0/8</ip>
                <ip>172.0.0.0/8</ip>
                </networks>
        <profile>default</profile>
        <quota>default</quota>
                 <allow_databases>
                    <database>testu1</database>
                    <database>testu3</database>
                    <database>testu2</database>
                </allow_databases>
            </testuser3>
</users>
```

**Comment by jasondavindev** [comment]
@dengc367 It's not working

I keep getting errors:
![Screenshot from 2021-06-14 16-52-09](https://user-images.githubusercontent.com/33331415/121951210-02437900-cd31-11eb-9b9c-809c91c4882c.png)

docker-compose
```yaml
services:
  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: sqlpad
    ports:
      - "3001:3000"
    environment:
     SQLPAD_AUTH_DISABLED: "true"
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: "admin"
    volumes:
      - sqlpad:/etc/sqlpad/seed-data

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:latest
    volumes:
      - $PWD/clickhouse/config/users.xml:/etc/clickhouse-server/users.xml
```

users.xml
```xml
<users>
        <!-- If user name was not specified, 'default' user is used. -->
        <default>
            <password></password>
            <networks>
                <ip>::/0</ip>
            </networks>

            <!-- Settings profile for user. -->
            <profile>default</profile>
        </default>

        <sqlpad>
            <password>sqlpad</password>
            <networks>
                <ip>::/0</ip>
            </networks>

            <!-- Settings profile for user. -->
            <profile>default</profile>
        </sqlpad>
    </users>
```
