### ISSUE TITLE
[unixODBC][Driver Manager]Data source name not found, and no default driver specified

### ISSUE THREAD

**Issue by nistrup** [sqlpad/sqlpad#1151]
I'm running an Ubuntu 20.04 image on ARM64 architecture on an AWS EC2 instance.

I've build the SQL Pad image using `sudo docker build -t sqlpad/sqlpad-odbc --build-arg ODBC_ENABLED=true .` which worked and I'm successfully running the image using docker-compose with the following settings:

```
version: '3.5'
services:
  sqlpad:
    container_name: sqlpad
    image: "sqlpad/sqlpad-odbc:latest"
    restart: always
    ports:
      - 3000:3000
    environment:
      SQLPAD_ADMIN: "{redacted}"
      SQLPAD_ADMIN_PASSWORD: "{redacted}"
    volumes:
      - /mnt/sqlpad:/var/lib/sqlpad
```

I can easily open SQL Pad but when I try to establish a new connection to my Oracle database I get the following error:

`[unixODBC][Driver Manager]Data source name not found, and no default driver specified`

![image](https://user-images.githubusercontent.com/17565925/184172688-97e8e0dc-2129-4c87-b977-0b6ef6716621.png)

I'm not sure if this is relevant but I can easily connect to the database outside of the container using sqlalchemy in Python.
