### ISSUE TITLE
Save query Internal Server Error

### ISSUE THREAD

**Issue by Kerwin1202** [sqlpad/sqlpad#841]
When i want to save my query text. but sqlpad show " Internal Server Error",

Version: 5.6.0 in Docker.  There is no problem using version 4.4 before, just upgraded to the latest version

The newly created query is no problem to save, I save the old one sqlpad is error,  And I noticed that the newly created query id is in the form of guid, but the old one is a random string, I don’t know if it is related to this

Error Info:

`{
	"level": 30,
	"time": "2020-09-25T02:13:29.288Z",
	"pid": 1,
	"hostname": "xxx.xxx.com",
	"name": "sqlpad-web",
	"req": {
		"id": 34,
		"method": "PUT",
		"url": "/api/queries/Zp00kFFs7HnEZhcW"
	},
	"res": {
		"statusCode": 500
	},
	"err": {
		"type": "Error",
		"message": "failed with status code 500",
		"stack": "Error: failed with status code 500\n    at ServerResponse.onResFinished (/usr/app/node_modules/pino-http/logger.js:73:38)\n    at ServerResponse.emit (events.js:327:22)\n    at onFinish (_http_outgoing.js:723:10)\n    at onCorkedFinish (_stream_writable.js:673:5)\n    at afterWrite (_stream_writable.js:490:5)\n    at onwrite (_stream_writable.js:470:7)\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:101:10)"
	},
	"responseTime": 30,
	"msg": "request errored"
}`

**Comment by rickbergfalk** [comment]
Hi @Kerwin1202. New queries do save with a guid, but the column is a string to be compatible with old and new query ids. 

Are you running SQLPad using the embedded database (SQLite, which is used if `SQLPAD_BACKEND_DB_URI` is not set) or are you using a SQL Server/MySQL/Postgres backend?

Is it possible you'd be able to capture and post the body of the PUT request used to save the query? Don't need the exact values for some things (like ids or query text). This can be captured in Chrome if you open dev tools and open the network tab prior to attempting to save the query.

**Comment by Kerwin1202** [comment]
Hi,  i use the default databse type (sqlpad.sqlite)

Error save : 

```put:  
https://xxx.com:4300/api/queries/GTmr0P1l8ucadPQ1

body:
{
	"id": "GTmr0P1l8ucadPQ1",
	"name": "用户-信息",
	"connectionId": "PY57TyBGQeCzXkC1",
	"queryText": "select\n  top 100 Score,*\nfrom\n  BlogUser\n--  where\n--     id = 6318 or  id = 6128 or  id = 6186 or  id = 6083\norder by\n  RegisteredTime desc\n  \n  \n  ",
	"chart": {
		"fields": {}
	},
	"createdBy": "nbva27WE4u935MBW",
	"updatedBy": "nbva27WE4u935MBW",
	"createdAt": "2019-09-28T06:47:18.246Z",
	"updatedAt": "2020-04-14T15:21:53.893Z",
	"tags": [],
	"acl": [
		{
			"id": 11,
			"queryId": "GTmr0P1l8ucadPQ1",
			"userId": null,
			"groupId": "__EVERYONE__",
			"write": true,
			"createdAt": "2020-05-23T01:25:06.215Z",
			"updatedAt": "2020-05-23T01:25:06.215Z"
		}
	],
	"createdByUser": {
		"id": "nbva27WE4u935MBW",
		"name": null,
		"email": "me@xxxx.com"
	},
	"updatedByUser": {
		"id": "nbva27WE4u935MBW",
		"name": null,
		"email": "me@xxx.com"
	},
	"canRead": true,
	"canWrite": true,
	"canDelete": true
}


reponse:
{"title":"Internal Server Error"}


docker logs:
 {
	"level": 30,
	"time": "2020-09-26T13:24:48.514Z",
	"pid": 1,
	"hostname": "sp.xxx.cn",
	"name": "sqlpad-web",
	"req": {
		"id": 728,
		"method": "PUT",
		"url": "/api/queries/GTmr0P1l8ucadPQ1"
	},
	"res": {
		"statusCode": 500
	},
	"err": {
		"type": "Error",
		"message": "failed with status code 500",
		"stack": "Error: failed with status code 500\n    at ServerResponse.onResFinished (/usr/app/node_modules/pino-http/logger.js:73:38)\n    at ServerResponse.emit (events.js:327:22)\n    at onFinish (_http_outgoing.js:723:10)\n    at onCorkedFinish (_stream_writable.js:673:5)\n    at afterWrite (_stream_writable.js:490:5)\n    at onwrite (_stream_writable.js:470:7)\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:101:10)"
	},
	"responseTime": 25,
	"msg": "request errored"
}

```

Success save by newly created query:
```
put: https://xxxx.cn:4300/api/queries/c6147d2a-532f-41ad-9de8-28d4fe7f6be7

body:
{
	"id": "c6147d2a-532f-41ad-9de8-28d4fe7f6be7",
	"name": "test",
	"connectionId": "PY57TyBGQeCzXkC1",
	"queryText": "q",
	"chart": {
		"chartType": "",
		"fields": {}
	},
	"createdBy": "nbva27WE4u935MBW",
	"updatedBy": "nbva27WE4u935MBW",
	"createdAt": "2020-09-26T13:28:12.774Z",
	"updatedAt": "2020-09-26T13:28:12.774Z",
	"tags": [],
	"acl": [],
	"createdByUser": {
		"id": "nbva27WE4u935MBW",
		"name": null,
		"email": "me@xxxx.com"
	},
	"updatedByUser": {
		"id": "nbva27WE4u935MBW",
		"name": null,
		"email": "me@xxxx.com"
	},
	"canRead": true,
	"canWrite": true,
	"canDelete": true
}

response:
{
	"id": "c6147d2a-532f-41ad-9de8-28d4fe7f6be7",
	"name": "test",
	"connectionId": "PY57TyBGQeCzXkC1",
	"queryText": "q",
	"chart": {
		"chartType": "",
		"fields": {}
	},
	"createdBy": "nbva27WE4u935MBW",
	"updatedBy": "nbva27WE4u935MBW",
	"createdAt": "2020-09-26T13:28:12.774Z",
	"updatedAt": "2020-09-26T13:28:18.065Z",
	"tags": [],
	"acl": [],
	"createdByUser": {
		"id": "nbva27WE4u935MBW",
		"name": null,
		"email": "me@xxxx.com"
	},
	"updatedByUser": {
		"id": "nbva27WE4u935MBW",
		"name": null,
		"email": "me@xxxx.com"
	},
	"canRead": true,
	"canWrite": true,
	"canDelete": true
}
```


by this dockerfile:  (`SQLPAD_DEBUG` and `SQLPAD_TABLE_CHART_LINKS_REQUIRE_AUTH`  they were deprecated in 5.6, so I didn’t write it below )
```
version: '2'

services:


  sqlpad:
    image: "sqlpad/sqlpad:latest"
    restart: always
    container_name: sqlpad
    hostname: sp.xxxx.cn
    environment:
      CERT_PATH: "/xxx.pem"
      KEY_PATH: "/xxx.key"
      SQLPAD_HTTPS_PORT: 3000
      SQLPAD_SESSION_MINUTES: 1440  # Minutes to keep a session active. Will extended by this amount each request.
      SQLPAD_TIMEOUT_SECONDS: 300  # HTTP server timeout as number of seconds. Extend as necessary for long running queries.
      SQLPAD_ALLOW_CONNECTION_ACCESS_TO_EVERYONE: 'false'  # Allows access on every connection to every user.
      SQLPAD_QUERY_HISTORY_RETENTION_PERIOD_IN_DAYS: 30  # Query history entries created before the retention period will be deleted automatically.
      SQLPAD_QUERY_HISTORY_RESULT_MAX_ROWS: 1000 # By default query history results are limited to 1,000 records.
      
    ports: 
      - 4300:3000
    volumes:
      - "/volume1/docker/sqlpad/data:/var/lib/sqlpad"
```
