### ISSUE TITLE
Issue configuring OIDC connection (identity server 4)

### ISSUE THREAD

**Issue by albertoVieiraNeto** [sqlpad/sqlpad#930]
Hi, i'm trying to configure this project to authenticate with a identity server 4 project (oidc), after configuring everything i'm getting the "login with oidc" button, when accessing the docker port (3000), the redirect to the Identity server ocurrs normaly and the return url also works, but when i get back to the sqlpad, it just shows "internal server error".  Looking at the docker console i'm seeing a "InternalOAuthError" (pasted bellow) 

```
InternalOAuthError: failed to obtain access token
sqlpad_1  |     at /usr/app/node_modules/passport-openidconnect/lib/strategy.js:93:38
sqlpad_1  |     at /usr/app/node_modules/oauth/lib/oauth2.js:191:18
sqlpad_1  |     at ClientRequest.<anonymous> (/usr/app/node_modules/oauth/lib/oauth2.js:162:5)
sqlpad_1  |     at ClientRequest.emit (events.js:315:20)
sqlpad_1  |     at TLSSocket.socketErrorListener (_http_client.js:426:9)
sqlpad_1  |     at TLSSocket.emit (events.js:315:20)
sqlpad_1  |     at emitErrorNT (internal/streams/destroy.js:92:8)
sqlpad_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
sqlpad_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
sqlpad_1  | InternalOAuthError: failed to obtain access token

```

Identity server Client

```` C#

                new Client
                {
                    ClientId = "SqlPadClient",

                    ClientSecrets = { new Secret("4922DE1F-7258-479B-8F55-0C95D9BDE8A9".Sha256()) },

                    AllowedGrantTypes = GrantTypes.CodeAndClientCredentials,

                    RedirectUris = { "http://localhost:3000/auth/oidc/callback" },                  

                    AllowOfflineAccess = true,
                    RequirePkce = false,

                    AllowAccessTokensViaBrowser = true,

                    AllowedScopes = {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.OfflineAccess,
                        IdentityServerConstants.StandardScopes.Email,
                        "WEBAPIPORTAL"
                    }
                },
````

docker file for OIDC

````
version: '3'
services: 
  sqlpad:
    # To use Dockerfile at root of this project, use build instead of image
    # build: ../../
    image: sqlpad/sqlpad:5
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
    environment:      
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_USERPASS_AUTH_DISABLED: 'true'
      SQLPAD_CONNECTIONS__sqlserverdemo__name: SQL Server Demo
      SQLPAD_CONNECTIONS__sqlserverdemo__driver: sqlserver
      SQLPAD_CONNECTIONS__sqlserverdemo__host: mssql
      SQLPAD_CONNECTIONS__sqlserverdemo__database: master
      SQLPAD_CONNECTIONS__sqlserverdemo__username: '<USER>'
      SQLPAD_CONNECTIONS__sqlserverdemo__password: '<PASSWORD>'
      #conexao oidc
      PUBLIC_URL: 'http://localhost:3000'
      SQLPAD_OIDC_CLIENT_ID: 'SqlPadClient'
      SQLPAD_OIDC_CLIENT_SECRET: '4922DE1F-7258-479B-8F55-0C95D9BDE8A9'
      SQLPAD_OIDC_ISSUER: 'https://localhost:5001'
      SQLPAD_OIDC_AUTHORIZATION_URL: 'https://localhost:5001/connect/authorize'
      SQLPAD_OIDC_TOKEN_URL: 'https://localhost:5001/connect/token'
      SQLPAD_OIDC_USER_INFO_URL: 'https://localhost:5001/connect/userinfo'
      SQLPAD_ALLOWED_DOMAINS: 'localhost'
      SQLPAD_OIDC_LINK_HTML: 'Connect with OIDC'

````

Can anyone help me with this? i already took a look at both libraries passport-openidconnect and oauth but could not figure out anything "glaring".
